version: "3.9"
services:
  mariadb:
    image: "mariadb:10.11.2"
    restart: "always"
    volumes: 
      - maria-data:/var/lib/mysql
    env_file:
      - .env  
    expose:
      - 3306
    networks:
      - docker-service
  backend:
    image: backend/dev
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "3020:3020"
    volumes:
      - ./src:/app/src
    depends_on:
      - mariadb
    environment:
      NODE_ENV: development
    networks:
      - docker-service

networks:
  docker-service:
    driver: bridge

volumes:
  maria-data: