version: "3.9"
services:
  webapp:
    image: webapp/dev
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "3010:3010"
    volumes:
      - ./src:/app/src
    environment:
      NODE_ENV: development